apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "alicloudmonitoring.labels" . | nindent 4 }}
  name: {{ template "alicloudmonitoring.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "alicloudmonitoring.matchLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.annotations }}
      annotations:
        {{- toYaml .Values.annotations | nindent 8 }}
      {{- end }}  
      labels:
        {{- include "alicloudmonitoring.matchLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      containers:
      - name: alicloudmonitoring
        {{- with .Values.args }}
        args: {{ toYaml . | nindent 8 }}
        {{- end }}        
        {{- with .Values.cmds }}
        command: {{ toYaml . | nindent 8 }}
        {{- end }}        
        image: {{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        {{- with .Values.ports }}
        ports: {{ toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.resources }}
        resources: {{ toYaml . | nindent 10 }}
        {{- end }}
