apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    {{- include "alicloudmonitoring.labels" . | nindent 4 }}
    {{- toYaml .Values.prometheusRule.labels | nindent 4 }}
  name: {{ template "alicloudmonitoring.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  groups:
    {{- toYaml .Values.prometheusRule.groups | nindent 4 }}
